### ISSUE TITLE
Autopilot: List of Issues

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#463] opened 2021-03-16 17:37 UTC
**In this post I will collect all serious AP issues I encounter.**
Last update of this list: **27.04.21**

ISSUE NUMBER 1!:
- [x] This bird is starting to make real fun!

(!) On Approach (!)
- [ ] Pitch and Roll-Mode get erased at around 1500 ft.
On ILS Allpraoch this will result in losing the ILS guidance below 1500 ft.

(!) HDG SEL (!)
- [ ] Bug: When switching from LNAV to HDG SEL the FMA is still showing "LNAV".

Flight Level Change:
- [ ] Bug: A/T is constantly moving throttles slightly up and down during descend with FLC.
- [ ] Instead, thrust should retard and eventually switch to HOLD during descend, see FCOM 4.10.7

![image](https://user-images.githubusercontent.com/78870770/116009153-3a271d80-a618-11eb-97c9-274ca26c816c.png)
- [x] Thrust mode THR REF should engage during climb.
- [x] According FMA for active thrust mode in left column should be shown.
- [x] Bug: FLC will level off during take off for no reason, engaging ALT HOLD (before selected MCP ALT has been reached). 

Magenta speed-bug: 
- [ ] Will flicker and the A/T will get erratic
due to the fact that VNAV wants to bug for the CRZ SPD
even if the flaps have not been fully retracted yet:
https://youtu.be/2MqJ3pPfkTw

LOC button
- [ ] Bug: You always have to click it three times in order to arm/engage LOC.

APP button
- [ ] Bug: When pressing APP with the LOC already captured,
GS does not show armed. Instead LOC is showing armed, even though already engaged.

![747-400 - 2021-04-10 10 38 43](https://user-images.githubusercontent.com/78870770/114264137-7425dc00-99e9-11eb-9499-9dff39b3377b.png)

VS button
- [x] Bug: You always have to click it twice in order to switch from VNAV to VS

ALT HOLD button
- [x] Bug: You always have to click it twice in order to switch from VNAV to ALT HLD

Disconnecting the AP via Yoke switch:

- [ ] Bug: VNAV will switch to another mode when disconnecting the AP - problematic when flying RNAV approaches 
- [x] FDs should stay active.
- [x] Pitch and roll mode must not be deleted as they feed the FDs.
- [x] Disconnecting CMD should not disarm A/T. 
- [x] Disconnecting CMD should not erase the thrust mode.
- [x] The shortcut-command for the disconnect-switch on the yoke should get mapped.
> 
> Here is how the PFD looks like on PDMG 747 after disco AP:
>
![image](https://user-images.githubusercontent.com/78870770/115143511-11b38800-a048-11eb-9120-c3264ddbc45e.png)
>
> Here another example:
> https://youtu.be/bonryhQCFOU?t=609

When reaching CRZ ALT
- [x] Bug: Thrust-mode doesn't change over to SPD, leading to overspeed.

![747-400 - 2021-04-17 11 23 36](https://user-images.githubusercontent.com/78870770/115108555-76e87a00-9f71-11eb-9a00-b82fe40955dc.png)

TOGA
- [ ] Bug: Thrust mode "THR REF" missing during take off with TOGA (VNAV disarmed)
- [ ] Bug: TOGA pitch FD is not showing pitch for target speed V2+X

![747-400 - 2021-04-21 12 40 18](https://user-images.githubusercontent.com/78870770/115543397-9cdb8a80-a2a1-11eb-8580-1912409d8562.png)

- [ ] TOGA should show engaged, 
LNAV & VNAV should show armed 
before TOGA power is activated. 
Screenshot taken from PMDG 747:

![image](https://user-images.githubusercontent.com/78870770/114781421-eba49400-9d78-11eb-8e63-e49f7a6a2a69.png)

ALT HOLD
- [x] Bug: When FLC captures MCP ALT and ALT HOLD engages,
sometimes the thrust mode (FMA) remains THR REF and does not switch over to SPD:

![747-400 - 2021-04-13 13 57 08](https://user-images.githubusercontent.com/78870770/114548973-c02e8600-9c60-11eb-84ff-44c04a954678.png)

pitch mode VNAV SPD
> Must allow to open MCP SPD window.

pitch mode VNAV PTH
- [ ] Bug when reaching CRZ ALT with FLC (take off without VNAV):
Switching over to VNAV on CRZ ALT will result in a false thrust-mode "THR REF", causing overspeed.
- [x] Bug: Tends to level off at every waypoint (without altitude restriction), then failing to recapture descend.
- [x] Bug Again: Plane climbs out in VNAV PTH instead of VNAV SPD

Usb-hardware throttle
- [x] Please bypass while A/T armed and thrust-mode (other than HOLD) is active.
- [ ] Would it be possible to also bypass the usb-hardware throttle during active thrust-mode THR REF?
This would allow to keep your unmotorized hardware device synchronized with the A/T without interfering. 

Arming VNAV on ground with A/T armed:
- [x] Bug: Will engage A/T and spool up the engines (without showing a corresponding FMA).

Pitch mode TOGA:
- [x] Bug: Switches to ALT HOLD during take off (without VNAV armed).

A/T - as long as disarmed:
- [x] No thrust mode can be active.
- [x] This is also true while pitch mode = VNAV PTH or VANV SPD.

General AP Logic:

> Nothing must automatically change the pitch, 
except the announciated pitch-mode while CMD is engaged.

> Nothing must automatically change the roll, 
except the announciated roll-mode while CMD is engaged.

> Nothing must automatically change the thrust, 
except the announciated thrust-mode
while the A/T is not disarmed.

> The announciated thrust mode drives the throttles.
> The announciated roll and pitch modes drive the FDs.
> CMD drives the trim and the yoke, following the FDs.

What I believe would be the "king's way" to program the AP
> To program one module for every single FMA.
> Some modules will have almost the same code.
> For example ALT HOLD = VS set to zero
> Then to program, how the different moduls trigger...

**Comment by oMrSmith** [comment] 2021-04-17 22:58
Hey @mSparks43, just in case, you don't get notified:
I update this list basically every day and check the issues
that have been fixed.

**Comment by mSparks43** [comment] 2021-04-18 03:04
Yes thank you, I dont get notified when you edit it, but I am referring to it for the things left to do :+1:

**Comment by oMrSmith** [comment] 2021-04-18 12:52
Alrighty. Thanks for all your effort in writing the code.

**Comment by oMrSmith** [comment] 2021-04-24 22:07
Dear @mSparks43 thanks for the update of the APP page.
For some reason, the plane climbs out in VNAV PTH again.

I did a short test flight to capture the issue, amongst others:

https://youtu.be/6JlAMi6PXCE

**Comment by mSparks43** [comment] 2021-04-25 00:28
So this is where something strange starts happening
![image](https://user-images.githubusercontent.com/6773686/115976368-b153a780-a56d-11eb-922e-01c0c2c88b5c.png)
VNAV is not showing as armed on the PFD (despite the light on the switch being lit)
what exactly did you do up to this point?

**Comment by oMrSmith** [comment] 2021-04-25 11:04
This was my test route.
![image](https://user-images.githubusercontent.com/78870770/115991029-a9742180-a5c6-11eb-9a70-04a6bf95a5cd.png)

**Comment by oMrSmith** [comment] 2021-04-25 12:42
Hey @mSparks43 here is the next test. I included the FMC setup in the video.
This time VNAV was showing armed, but right before VNAV SPD engaged,
TOGA get's lost and the thrust-mode shortly changed to SPD.
https://youtu.be/eQbHRKZzEwc

**Comment by mSparks43** [comment] 2021-04-25 13:05
ahhh, I think the cause may well be dep and arr at the same airport, should be enough to recreate now

**Comment by oMrSmith** [comment] 2021-04-25 16:40
Hey @mSparks43 I just retested my last flight (GCLP-GCXP). Take off went very well and the plane climbed out in VNAV SPD. Thanks man! One new issue seems to be born: During descend, VNAV would bug for speeds higher than the speed restriction of 250 knots below 10.000 feet.

**Comment by mSparks43** [comment] 2021-04-25 18:52
what speed were you at the 11,000? the speed bug will fall at a max 15kts per 500 feet during descent to keep the rates of change sensible, so if you were above 280kts at 11,000 it will still be higher than 250kt at e.g. 9,750

**Comment by oMrSmith** [comment] 2021-04-25 19:11
So before the update VNAV would bug for 250 knots immediately 
when descending below 10.000 feet (magenta speed bug on speed tape).
On my last test-flight (where the take off worked perfect) VNAV would bug for speeds like 262 knots
even though I was already below 10.000 feet.

**Comment by oMrSmith** [comment] 2021-04-26 08:33
Hey @mSparks43 I think this causes that VNAV PTH will no longer initiate the descend
when crossing the T/D: 
https://youtu.be/MAOWfL-RfaQ

**Comment by mSparks43** [comment] 2021-04-26 09:06
Progress page would show you how far you are from TOD, alt push wont do anything if you are more than 50 nm from TOD, and you were still 30nm from the lower waypoint

**Comment by oMrSmith** [comment] 2021-04-26 10:02
Ah. I think I found the issue. The little green dot is still showing the correct T/D but the FMC
miscalculates the T/D, putting it further away than the destination:
![747-400 - 2021-04-26 11 59 43](https://user-images.githubusercontent.com/78870770/116065380-40081780-a687-11eb-98e0-26b88e1715fb.png)
PS: The DEST is miscalculated too. It is including the whole missed appraoch in its calculation.

**Comment by mSparks43** [comment] 2021-04-26 10:27
kinda.
you are only 60nm from GCXO, but there is still 154nm before you reach it in your flight plan and you are 65nm to begin the descent to it.

What you are seeing is a known issue with the TOD calc (although the green TOD dot on the ND is incorrect 90% of the time and cannot be removed), where it uses the end of descent to calculate the TOD rather than the altitude of the first waypoint in a descent, depending on how xplane loads these up, you'll often see this as a strange descent profile to the first waypoint after descent begins.

Its exaggerated in this approach because the length of low altitude journey (should be lower much sooner than a simple idle descent to the airport)

You'll see this addressed where there are changes to this function 
https://github.com/mSparks43/747-400/blob/d928c1fcb26361cb19f6b27aeef423912f905f5b/plugins/xtlua/scripts/B747.70.xt.autopilot/B747.70.xt.autopilot.lua#L1769

**Comment by oMrSmith** [comment] 2021-04-26 10:35
The thing is this: The figure 154nm is false! 
If you add the distances between the LEGs from start to DEST RW you get 67nm: 1+7+5+6+35+6+7.
The progress page has never shown the correct distance. It adds the missed approach which results in a much longer route.

**Comment by mSparks43** [comment] 2021-04-26 10:46
the 154nm is xplanes estimate, the distance to TOD doesn't use this figure, its the TOD (roughly) to reach the End of Descent waypoint on the VNAV descent page.

This latest fix 
https://github.com/mSparks43/747-400/commit/d928c1fcb26361cb19f6b27aeef423912f905f5b
only made it skip activating FMC altitudes for the "alt select" option on the legs page that are less than 1000 feet higher than current altitude (e.g. it will ignore the 400feet altitude hold when you are at 150feet (which is what was causing the AP to switch to hold while you were taking off), anything else is unrelated.

**Comment by oMrSmith** [comment] 2021-04-26 10:50
I see. Still a T/D of 65nm for a route which is only 67nm long is kinda strange ;).
But I'll do more testing. Maybe I'll simply have to load a cessna and every thing is fine again.

**Comment by mSparks43** [comment] 2021-04-26 10:54
but aren't you at like 11,000 feet? you only need to lose 6000 feet which at 2000fpm will take 3 minutes.

**Comment by oMrSmith** [comment] 2021-04-26 11:05
I think the problem is this: The value for the EoD 
(which the ToD is based on as you say)
does not resemble 
the sum of the distances between the LEGs page from start to DEST RW.

If I take the rule of thumb I would need at least 27nm of distance
to lose 9000 feet (3nm for every 1000ft). Adding 10nm this would give me a ToD of 30...
(airport elevation = 2000)

**Comment by mSparks43** [comment] 2021-04-26 11:09
I think what probably happening with that EoD calc, is you are within 60nm of the programmed ToD, at which point it will calculate current ToD from your current altitude rather than the programmed one, this is to prevent it switching into "within 50nm of ToD" mode (which locks out further climbing) before you finish climbing on short hops.

**Comment by oMrSmith** [comment] 2021-04-26 12:37
Here's another example:
101nm of route distance versus 98nm ToD. 
![image](https://user-images.githubusercontent.com/78870770/116083075-7e5c0180-a69c-11eb-8bb1-83f9ef121bb9.png)
![747-400 - 2021-04-26 14 30 46](https://user-images.githubusercontent.com/78870770/116083190-a51a3800-a69c-11eb-89ca-6ec51d7232ab.png)

**Comment by mSparks43** [comment] 2021-04-26 13:04
again related to the function already mentioned, you can get continuous output of the current total distance and TOD distance from destination airport from that by removing the two minus signs from
https://github.com/mSparks43/747-400/blob/d928c1fcb26361cb19f6b27aeef423912f905f5b/plugins/xtlua/scripts/B747.70.xt.autopilot/B747.70.xt.autopilot.lua#L1796

cruiseTOD or currentTOD are subtracted from B747BR_totalDistance to give distance to TOD

**Comment by oMrSmith** [comment] 2021-04-26 13:29
What baffels me is that in all my previous test flights the plane would always start the descend when crossing the little green dot.
Infact the VNAV descend had been very reliable...

**Comment by mSparks43** [comment] 2021-04-26 14:41
here https://github.com/mSparks43/747-400/commit/36d3693a1fdeda847f8c9b46790dc630c1c54316 a valid EOD index was increased from 5nm to 10nm from the airport, that could have increased the EOD height from that of the airport to the 4300 feet of the approach waypoints

**Comment by mSparks43** [comment] 2021-04-26 17:27
There is however a bug related to https://github.com/mSparks43/747-400/commit/48ebbe1db79b6cf41f71caef78b9c589b6f6629a, fix coming soon. (never sets lower alts)

**Comment by oMrSmith** [comment] 2021-04-26 17:50
Cool. I'll test once it's out.

**Comment by oMrSmith** [comment] 2021-04-26 20:45
Just as an info for you:

![image](https://user-images.githubusercontent.com/78870770/116147930-9a819200-a6e0-11eb-8c1a-57bd260afe7b.png)

I programmed the route of the upper picture into the FMC again. 
This time _I erased the missed approach out of the LEGs page_:
All of a sudden the distance to the DEST on the progress page
resembles the calculated route distance of Little Navmap:

![747-400 - 2021-04-26 22 40 27](https://user-images.githubusercontent.com/78870770/116148156-d6b4f280-a6e0-11eb-877e-a68a479ee91f.png)

**Comment by mSparks43** [comment] 2021-04-26 21:51
before release I'll replace xplane distance to airport with a properly calculated one. Been fighting with lnav/vnav most of the evening, its not quite right yet. not descending was a brainfart moment (the change made it only set to fmc alt if it was higher than current alt, which of course never set lower alts)

**Comment by oMrSmith** [comment] 2021-04-26 22:18
Creating an own calculation for the DIST to the DEST sounds like a great idea! I can imagine: These things are very complex.
But let me tell you this as a compliment for the work of you and the team: I own the payware 747 by SSG, which has been out for quite a while and has received a relatively solid AP meanwhile. Despite that, I think the sparky 747 looks, feels, flies and sounds much better already! The FMC is better too.

**Comment by oMrSmith** [comment] 2021-04-27 10:13
Thanks for fixing the VS and ALT HLD button. Yet another significant improvement!

**Comment by oMrSmith** [comment] 2021-04-27 11:02
Dear @mSparks43 I wanted to report another issue 
that I noticed before but didn't understand the trigger 
until my test-flight today:

The magenta speed-bug will flicker and the A/T will get erratic 
when VNAV wants to bug for the CRZ SPD
even though the flaps have not been fully retracted yet:

https://youtu.be/2MqJ3pPfkTw

**Comment by crazytimtimtim** [comment] 2021-04-27 14:40
> Dear @mSparks43 I wanted to report another issue [...]

I haven't watched your video yet, but I have this problem when I set the speed bug anywhere in the red oversees zone.

**Comment by mSparks43** [comment] 2021-04-28 08:59
This is caused by "fighting" between what you have set and the FEP, but since all there is to go on for FEP is
![image](https://user-images.githubusercontent.com/6773686/116376422-863cb280-a810-11eb-854c-0e8f230dd841.png)

its not clear exactly _how_ it should behave (or even if it would truly let you program an over speed in the first place)
closing this issue because afaict the issues identified originally have been fixed, please open new ones for individual specific issues

**Closed by mSparks43** 2021-04-28 08:59 UTC

**Comment by oMrSmith** [comment] 2021-04-28 10:14
Hey @mSparks43 I have checked all issues that have been fixed, which means
that all issues that have not been checked (checkbox) are still present.
Do you want me to separate these into individual issues?
Until now I was basically testing daily making sure to check all issues fixed.

**Comment by oMrSmith** [comment] 2021-04-28 10:24
> its not clear exactly _how_ it should behave

PS: I think VNAV should not bug for speeds higher than the current flap setting allows.
It works the same way downwards.

**Comment by crazytimtimtim** [comment] 2021-04-28 13:09
> PS: I think VNAV should simply not bug for speeds higher than the current flap setting allows.

I agree. This shouldn't be _too_ difficult to implement. Also, why is this closed? There are still a few boxes to check.

**Comment by mSparks43** [comment] 2021-04-28 23:43
> Do you want me to separate these into individual issues?

Please, easier to work on them one at a time, the speedbug fighting in IAS mode and LOC button will probably have to wait until either after the next release or after the beta announce, because there is to much opportunity to break things there, the others need more detail and this thread is already quite confused.
and for example
 Bug: When switching from LNAV to HDG SEL the FMA is still showing "LNAV".
should already be fixed,

**Comment by oMrSmith** [comment] 2021-04-29 10:08
You write the code. If working is easier for you this way, I'll do it this way.
I just hope, that this post won't get deleted as I'm still refering to it as an overview...
Thanks for fixing the LNAV issue.
PS: If the speed bug could make a "false" decision - as a first step to solve the issue - 
I think this would be better than making no decision, as this get's the pilot confused.

**Comment by oMrSmith** [comment] 2021-04-29 17:05
Guys, do you know, how I can open the normal LEGs page during flight?
If I click the LEGS button on the FMC during flight, I'll only get
the LEGs page with the ACT DCT-TO function. This has the disadvantage 
that the target speeds are not shown. Hence they can not be changed in the FMC...

**Comment by crazytimtimtim** [comment] 2021-04-29 17:15
> Guys, do you know, how I can open the normal LEGs page during flight?
> If I click the LEGS button on the FMC _during flight_, I'll only get
> the LEGs page with the ACT DCT-TO function. This has the disadvantage
> that the target speeds are not shown. Hence they can not be changed in the FMC...

lmao that would've been fixed if mSparks merged my pull request #462. Anyway it seems, according to the updated readme, that you can do this: "Once in the air, the xplane LEGS page can be reached by pressing RTE, and then L6 (marked RTE 2)"

**Comment by oMrSmith** [comment] 2021-04-29 19:15
Ah I see, thanks for the info I'll try that.

**Comment by oMrSmith** [comment] 2021-05-04 17:37
Hey guys, do you have a tip on how to 
get the right trim setting for take off?

PS: To be in the green area alone
doesn't seem to be enough to prevent the alarm ;)...

**Comment by mSparks43** [comment] 2021-05-04 22:50
R4 on the takeoff page
![image](https://user-images.githubusercontent.com/6773686/117079322-d1d4ec00-ad3b-11eb-9807-1655eaf1dae8.png)

**Comment by oMrSmith** [comment] 2021-05-04 23:11
Ahaaaaaaaaaa! I wasn't aware that I'd have to click next to CG to get the trim value. Thank you!
