### ISSUE TITLE
Approach REF shows up late on PFD

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#489] opened 2021-04-13 12:05 UTC
![747-400 - 2021-04-13 14 07 52](https://user-images.githubusercontent.com/78870770/114550920-0684e480-9c63-11eb-923b-109d1f828a58.png)

**Comment by oMrSmith** [comment] 2021-04-13 12:11
Update: Shows up later...

**Comment by mSparks43** [comment] 2021-04-13 14:28
Possible duplicate of #262

**Comment by MCCVeen** [comment] 2021-04-14 11:34
> Possible duplicate of #262

Nope mines about having the Flap 25 bug displayed when flaps 30 is selected and his is about missing the REF bug :)

**Comment by oMrSmith** [comment] 2021-04-17 22:38
It seems like the APP REF (flaps and landing speed) does not show up on PFD
until the landing flaps get actually configured.

**Comment by mSparks43** [comment] 2021-04-18 03:27
I believe this is the correct functionality
![image](https://user-images.githubusercontent.com/6773686/115133180-82d24b80-a006-11eb-9178-b099f4558900.png)
However, as per #262 its actually displaying to much.

**Comment by oMrSmith** [comment] 2021-04-18 10:27
Ahh! You see:
The REF speed bug being delayed makes perfect sense to me.
I just thought that the figure "30/132" should show up in the PFD
ones the landing config has been selected in the FMC.

![115133180-82d24b80-a006-11eb-9178-b099f4558900](https://user-images.githubusercontent.com/78870770/115142304-55ef5a00-a041-11eb-8ffd-cace9806d54f.png)

**Comment by mSparks43** [comment] 2021-04-18 11:58
>I just thought that the figure "30/132" on the bottom left of the PFD

Depends on the avionics version
![image](https://user-images.githubusercontent.com/6773686/115144664-298e0a80-a04e-11eb-9754-c79f25c45a21.png)

**Closed** 2021-04-24 19:14 UTC

**Comment by oMrSmith** [comment] 2021-05-06 12:45
Hey @mSparks43 

I wanted to ask: Has the last word on the approach REF already been spoken?

I think: The version which shows the final approach SPD on the PFD
_as soon as it has been entered into the APPR page_
is by far the better system... 

![image](https://user-images.githubusercontent.com/78870770/117299364-c1765b80-ae78-11eb-89f7-1f20edadc739.png)

Here is why I think so:

It is crucial to _be aware_  of your target speed
_ahead of time_ and _during the whole approach_
in order to manage the SPD with success.
Having this figure on the PFD 
(before being in that speed range)
makes life much easier. 
Also: It is one figure less to remember
and more comfortable than to look on the FMC...

What do you think?

**Comment by mSparks43** [comment] 2021-05-06 14:51
While I'm not 100% sure of the question, I think the answer is that
R1, R2 and R4 work on the approach page now
![image](https://user-images.githubusercontent.com/6773686/117319021-36529100-ae8b-11eb-942e-6975dc62c947.png)

which will put "REF" on the PFD once set on R4.

**Comment by oMrSmith** [comment] 2021-05-06 15:14
"will put 'REF' on the PFD once set on R4"
If this will print the figure 30/166 on the PFD,
then that's exactly what I mean :D !

**Comment by oMrSmith** [comment] 2021-05-08 13:02
What I wanted to say is this:

I believe the best PFD version is the one

_that will show the approach REF
in the bottom left corner of the PFD
as soon as the landing configuration
has been selected in the APPROACH page_.

Like so:

![image](https://user-images.githubusercontent.com/78870770/117540206-4d6dbc00-b00e-11eb-9726-86124c33494a.png)

**Comment by oMrSmith** [comment] 2021-05-23 14:20
Dear @mSparks43 

normally
 
_as soon as_ 
you enter the approach configuration in the APP PAGE
it shows up in the bottom left corner of the PFD:

![image](https://user-images.githubusercontent.com/78870770/119264227-8dbe6400-bbe2-11eb-80b9-33640e5958ec.png)

I find this extremely helpful...

Just for my understanding:
Have you decided against this variant?

**Comment by mSparks43** [comment] 2021-05-23 21:18
> Have you decided against this variant?

there's stuff in there to do this by livery/as a sim config option. those values are now available as datarefs, but pretty sure that isn't the only difference of this variant (e.g. Baro is bottom right, and I think on current is top right), so it will need all the bits adding to pfd.
- in a later release.

**Comment by oMrSmith** [comment] 2021-05-24 09:43
I see. Thanks for letting me know.
