### ISSUE TITLE
GS and Exp LOC always displayed on PFD

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#217] opened 2020-12-24 06:39 UTC
The GS and LOC indications are always displayed on the PFD. They should only be displayed with an ILS frequency tuned into the FMC

![image](https://user-images.githubusercontent.com/75425109/103067403-1c3ea300-45bb-11eb-8a9d-adfe4085c2ae.png)
![image](https://user-images.githubusercontent.com/75425109/103067340-f0bbb880-45ba-11eb-9d08-0e2a287c9042.png)
![image](https://user-images.githubusercontent.com/75425109/103067370-07620f80-45bb-11eb-906a-316f8086c9c2.png)
![image](https://user-images.githubusercontent.com/75425109/103067389-13e66800-45bb-11eb-9d30-f0e326396209.png)

**Comment by mSparks43** [comment] 2020-12-27 05:45
duplicate of #193

**Closed by mSparks43** 2020-12-27 05:45 UTC
