### ISSUE TITLE
Flaps reference bugs

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#617] opened 2021-06-26 15:35 UTC
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [x] Screenshot included (where applicable)

Flap 25 reference bug will only show when flap 25 is selected
Flap 20 reference bug will not be shown when flaps 30

![image](https://user-images.githubusercontent.com/75425109/123517485-84249200-d6a1-11eb-8da1-1a8422311eb8.png)
![image](https://user-images.githubusercontent.com/75425109/123517497-9e5e7000-d6a1-11eb-96bb-9c10943bd1ae.png)
![image](https://user-images.githubusercontent.com/75425109/123518134-cdc2ac00-d6a4-11eb-8c31-a7737f388dbe.png)
![image](https://user-images.githubusercontent.com/75425109/123518145-da470480-d6a4-11eb-84e0-ca482feb2062.png)

**Comment by mSparks43** [comment] 2021-06-26 23:08
probable duplicate of #489
screenshot match
![image](https://user-images.githubusercontent.com/78870770/119264227-8dbe6400-bbe2-11eb-80b9-33640e5958ec.png)
and
![115133180-82d24b80-a006-11eb-9178-b099f4558900](https://user-images.githubusercontent.com/78870770/115142304-55ef5a00-a041-11eb-8ffd-cace9806d54f.png)

**Closed by mSparks43** 2021-06-26 23:08 UTC

**Comment by MCCVeen** [comment] 2021-06-27 04:00
> probable duplicate of #489
> screenshot match
> ![image](https://user-images.githubusercontent.com/78870770/119264227-8dbe6400-bbe2-11eb-80b9-33640e5958ec.png)
> and
> ![115133180-82d24b80-a006-11eb-9178-b099f4558900](https://user-images.githubusercontent.com/78870770/115142304-55ef5a00-a041-11eb-8ffd-cace9806d54f.png)

Has absolutely nothing to do with eachother, please reopen.

**Comment by Matt726-S** [comment] 2021-06-27 04:07
you can see in this video, obet has flaps 30 selected, and it matched what @MCCVeen is saying

**Comment by mSparks43** [comment] 2021-06-27 09:32
https://github.com/mSparks43/747-400/issues/262

**Comment by MCCVeen** [comment] 2021-06-27 11:46
> #262
> 
> > in this video
> 
> They are LCDs, as per #489 the behaviour depends on the avionics version, so without a proper reference of exactly how they display in each version - and support for different avionics versions - there is nothing more I can really do here.

Same on CRT as LCD.

**Comment by MCCVeen** [comment] 2021-06-27 11:48
Like I said

![image](https://user-images.githubusercontent.com/75425109/123543343-43368700-d74e-11eb-8be3-543825bb60bf.png)

**Comment by mSparks43** [comment] 2021-06-27 12:10
> Like I said
> 
> ![image](https://user-images.githubusercontent.com/75425109/123543343-43368700-d74e-11eb-8be3-543825bb60bf.png)

fixed in #262 and #489

![image](https://user-images.githubusercontent.com/6773686/123543911-1afc5780-d751-11eb-8782-c22bbf09e243.png)

>Flap 25 reference bug will only show when flap 25 is selected

yes, as is now

>Flap 20 reference bug will not be shown when flaps 30

This is Flaps 30, from #489 
![115133180-82d24b80-a006-11eb-9178-b099f4558900](https://user-images.githubusercontent.com/78870770/115142304-55ef5a00-a041-11eb-8ffd-cace9806d54f.png)
