### ISSUE TITLE
Fplan legs arrangement

### ISSUE THREAD

**Issue by mrshiljo** [mSparks43/747-400#737] opened 2021-12-17 05:05 UTC
There is a problem when sorting out legs, specialy when its first one on page, and you have to tranfer it on page before on last row in boxes, you cant, FMC gives not known message, or transfer that point in direct to box...And you cant cy<cle on plan mode thru each waypoint respectively...only by next page, so 6 points ahead

**Comment by mSparks43** [comment] 2021-12-19 02:24
Duplicate of #724

**Closed by mSparks43** 2021-12-19 02:24 UTC
