### ISSUE TITLE
no “>AUTOTHROTTLE DISC” when using throttle disconnect buttons

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#464] opened 2021-03-16 17:58 UTC
when you push the autothrottle disconnect for either of the buttons on the throttles, and eicas message that says >AUTOTHROTTLE DISC should appear, and disengage the autothrottle. when you push one of the buttons again, the eicas message will disappear (it disappears 5 seconds after pushing the button the second time). the autothrottle still stays armed, until you disarm it with the switch on the MCP

**Comment by MCCVeen** [comment] 2021-03-17 03:38
Duplicate of issue #299

**Closed** 2021-03-18 12:45 UTC
